Colegio/Controllers/MateriaController.cs
using Colegio.Context;
using Colegio.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Colegio.Controllers
{
    public class MateriaController : Controller
    {
        private DataStore db = new DataStore();
        // GET: Materia
        public ActionResult Index()
        {
            return View(db.materias.ToList());
        }

        // GET: Materia/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                Materias x = db.materias.Find(id);
                if (x == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                else
                {
                    return View(x);
                }
            }
        }

        // GET: Materia/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Materia/Create
        [HttpPost]
        public ActionResult Create(Materias materia)
        {
            try
            {
                var reigstro = from a in db.materias
                               where a.nombre == materia.nombre
                           select new
                           {
                               a.nombre
                           };

                if (reigstro.Count() == 0)
                {
                    db.materias.Add(materia);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.error = "Ya existe una materia con el nombre de "+ reigstro.First().nombre;
                    return View(materia);
                }                
            }
            catch
            {
                return View(materia);
            }
        }

        // GET: Materia/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                Materias x = db.materias.Find(id);
                if (x == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                else
                {
                    return View(x);
                }
            }
        }

        // POST: Materia/Edit/5
        [HttpPost]
        public ActionResult Edit(Materias materia)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(materia).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(materia);

            }
            catch
            {
                return View(materia);
            }
        }

        // GET: Materia/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                Materias x = db.materias.Find(id);
                if (x == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                else
                {
                    return View(x);
                }
            }
        }

        // POST: Materia/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Materias materia)
        {
            try
            {
                    materia = db.materias.Find(id);
                    db.materias.Remove(materia);
                    db.SaveChanges();
                    return RedirectToAction("Index");
              }
            catch
            {
                return View(materia);
            }
        }
    }
}

Colegio/Controllers/NotasController.cs
using Colegio.Context;
using Colegio.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Colegio.Controllers
{
    public class NotasController : Controller
    {
        // GET: Notas
        private DataStore db = new DataStore();
        public ActionResult Index()
        {
            if (db.Asignaturas.Count() == 0)
            {
                ViewBag.message = "No se han asignado materias";
                return View();
            }
            else
            {
                ViewBag.message = " ";
                return View(db.estudiantes.ToList());
            }
            
        }

        // GET: Notas/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Notas/Create
        public ActionResult editNotas(Asignaturas asig, int? id,string nombremateria)
        {
            ViewBag.nombremateria = nombremateria;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                asig = db.Asignaturas.Find(id);            
                if (asig == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                else
                {                    
                    return View(asig);
                }
            }
        }

        // POST: Notas/Create
        [HttpPost]
        public ActionResult editNotas(Asignaturas asig, String idestudiante, int idmateria,int idprof)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    asig.idprofesor = idprof;
                    asig.idperson = Int32.Parse(idestudiante);
                    asig.idMateria = idmateria;
                    db.Entry(asig).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(asig);

            }
            catch
            {
                return View(asig);
            }
        }

        // GET: Notas/Edit/5
        public ActionResult Edit(int id)
        {

            var join = from a in db.Asignaturas  
                          join b in db.materias on a.idMateria equals b.IdMateria 
                          where a.idperson == id 
                          select new Join
                          {          
                             asignaturassVm = a,materiasvm =b
                          };
            ViewBag.idestudiante = id;
            return View(join);
        }

        // POST: Notas/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Notas/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Notas/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Colegio/Controllers/ProfesorController.cs
using Colegio.Context;
using Colegio.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Colegio.Controllers
{
    public class ProfesorController : Controller
    {
        private DataStore db = new DataStore();
        // GET: Profesor
        public ActionResult Index()
        {
            return View(db.profesores.ToList());
        }

        // GET: Profesor/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                Profesor x = db.profesores.Find(id);
                if (x == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                else
                {
                    return View(x);
                }
            }
        }

        // GET: Profesor/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Profesor/Create
        [HttpPost]
        public ActionResult Create(Profesor maestro)
        {
            try
            {
                ViewBag.error = null;
                var reigstro = from a in db.profesores
                               where a.nombre == maestro.nombre && a.apellido == maestro.apellido
                               select new
                               {
                                   a.nombre,
                                   a.apellido
                               };
                if (reigstro.Count() == 0)
                {
                    db.profesores.Add(maestro);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.error = "ya existe el estudiante " + reigstro.First().nombre + " " + reigstro.First().apellido;
                    return View(maestro);
                }
            }
            catch
            {
                return View(maestro);
            }
        }

        // GET: Profesor/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                Profesor x = db.profesores.Find(id);
                if (x == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                else
                {
                    return View(x);
                }
            }
        }

        // POST: Profesor/Edit/5
        [HttpPost]
        public ActionResult Edit(Profesor maestro)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(maestro).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(maestro);

            }
            catch
            {
                return View(maestro);
            }
        }

            // GET: Profesor/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                Profesor x = db.profesores.Find(id);
                if (x == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                else
                {
                    return View(x);
                }
            }
        }

        // POST: Profesor/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Profesor maestro)
        {
            try
            {
                maestro = db.profesores.Find(id);
                db.profesores.Remove(maestro);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View(maestro);
            }
        }
    }
 }

Colegio/Controllers/ReportController.cs
using Colegio.Context;
using Colegio.Models;
using Microsoft.Reporting.WebForms;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace Colegio.Controllers
{
    public class ReportController : Controller
    {
        // GET: Report
        private DataStore db = new DataStore();
        public ActionResult Index()
        {
            ReportViewer reportViewer = new ReportViewer();
            reportViewer.ProcessingMode = ProcessingMode.Local;
            reportViewer.SizeToReportContent = true;
            reportViewer.Width = Unit.Percentage(100);
            reportViewer.Height = Unit.Percentage(100);

            var join = from a in db.estudiantes
                       from b in db.materias
                       from c in db.Asignaturas
                       from d in db.profesores
                       where a.IdEstudiante == c.idperson && c.idMateria == b.IdMateria && d.IdProfesor == c.idprofesor
                       select new
                       {
                           nombre = a.nombre,
                           nombre1 = a.apellido,
                           nota1 = c.nota1,
                           nota2 = c.nota2,
                           nombre2 =d.nombre+" "+d.apellido
                            
                       };
            //var connectionString = ConfigurationManager.ConnectionStrings["Datastore"].ConnectionString;
            //String query = "select estudiantes.nombre,Materias.nombre,Asignaturas.nota1,Asignaturas.nota2,Profesors.nombre from estudiantes,Materias,Asignaturas,AsignaturasProfesores,Profesors where estudiantes.IdEstudiante = Asignaturas.idperson and asignaturas.idMateria = Materias.IdMateria  and Profesors.IdProfesor = Asignaturas.idprofesor";
            //SqlConnection conx = new SqlConnection(connectionString); SqlDataAdapter adp = new SqlDataAdapter(query, conx);
            //colegioDBDataSet ds = new colegioDBDataSet();
            //adp.Fill(ds, ds.Asignaturas.TableName);

            reportViewer.LocalReport.ReportPath = Request.MapPath(Request.ApplicationPath) + @"Reports\Report.rdlc";
            //reportViewer.LocalReport.DataSources.Add(new ReportDataSource("DataSet1", ds.Tables[0]));
            reportViewer.LocalReport.DataSources.Add(new ReportDataSource("DataSet1", join));


            ViewBag.ReportViewer = reportViewer;

            //var join = from a in db.estudiantes 
            //           from b in db.materias
            //           from c in db.Asignaturas
            //           from d in db.profesores
            //           where a.IdEstudiante == c.idperson && c.idMateria == b.IdMateria && d.IdProfesor ==c.idprofesor
            //           select new Join
            //           {
            //               estudiantevm =a,materiasvm=b,asignaturassVm=c,profesorvm=d
            //            };
            return View();
        }
    }
}

Colegio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SincoABR</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">SINCOABR</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">@Html.ActionLink("Estudiantes", "index", "Estudiante")&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</li>
                <li class="nav-item">
                    <a class="nav-link" href="#">@Html.ActionLink("Materias", "index", "Materia")</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">@Html.ActionLink("Profesores", "index", "Profesor")</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">@Html.ActionLink("Asignar materias", "index", "ASignaturas")</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">@Html.ActionLink("Asignar Notas", "index", "Notas")</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">@Html.ActionLink("Reporte Estudiantes", "index", "Report")</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </li>

            </ul>
            
        </div>
    </nav>

    @*<nav class="navbar navbar-expand-lg navbar-light bg-light">

          <A class="navbar-brand"> @Html.ActionLink("SincoABR", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</A>
                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                  </button>
              <div class="collapse navbar-collapse">
                  <ul class="navbar-nav mr-auto">
                      <li class="nav-item"><a class="nav-link>"@Html.ActionLink("Estudiantes", "index", "Estudiante")<span class="sr-only">(current)</span></a></li>
                      <li class="nav-item">@Html.ActionLink("Materias", "index", "Materia")</li> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                      <li class="nav-item">@Html.ActionLink("Profesores", "index", "Profesor")</li> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                      <li class="nav-item">@Html.ActionLink("Asignar materias", "index", "ASignaturas")</li> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                      <li class="nav-item">@Html.ActionLink("Asignar Notas", "index", "Notas")</li> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                      <li class="nav-item">@Html.ActionLink("Reporte", "index", "Report")</li> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  </ul>
              </div>

        </nav>*@
    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>